<a href="https://colab.research.google.com/github/MuktoFlame/ML-Journey/blob/main/00_PytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resource notebook : https://www.learnpytorch.io

Github : https://github.com/mrdbourke/pytorch-deep-learning

## Import Dependencies

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors

### Creating tensors

In [ ]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

In [ ]:
# Vector
vector = torch.tensor([7])
vector

tensor([7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([1])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8, 11],
                       [9, 10, 11]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 11]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Check number of dimensions
TENSOR.ndim

3

In [ ]:
# Check shape
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][1][1]

tensor(6)

### Random Tensors

In [ ]:
# Create a random tensor
random_tensor = torch.rand(2, 3, 4)
random_tensor, random_tensor.dtype

(tensor([[[0.8449, 0.5255, 0.8011, 0.1791],
          [0.6224, 0.1913, 0.5784, 0.8714],
          [0.6174, 0.8682, 0.7601, 0.1891]],
 
         [[0.9144, 0.2473, 0.6691, 0.9010],
          [0.3141, 0.7612, 0.0795, 0.4381],
          [0.5068, 0.5971, 0.1896, 0.6054]]]),
 torch.float32)

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim, random_tensor.dtype

(torch.Size([224, 224, 3]), 3, torch.float32)

### Zeros and Ones

In [ ]:
# Create a teansor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors like

In [ ]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-22-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start=0, end=101, step=5)

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big error I'll run into with PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float32 tensor
float_32 = torch.tensor([3.0, 6.0, 9.0],
                        dtype=None,
                        device=None,          # device="cpu"/"cuda"
                        requires_grad=False)  # PyTorch to track gradient
float_32, float_32.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16 = float_32.type(torch.float16)
float_16, float_16.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [ ]:
float_16 * float_32

tensor([ 9., 36., 81.])

In [ ]:
int_32 = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32, int_32.dtype

(tensor([3, 6, 9], dtype=torch.int32), torch.int32)

In [ ]:
float_16 * int_32

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [ ]:
float_32 * long_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

In [ ]:
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.5956, 0.5017, 0.1806, 0.4144],
        [0.7325, 0.0361, 0.9959, 0.9043],
        [0.7127, 0.9013, 0.4089, 0.3233]])

In [ ]:
# size is a funtion and shape is an attribute
rand_tensor.size(), rand_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
## Find out details about tensor
print(rand_tensor)
print(f"Datatype of Tensor: {rand_tensor.dtype}")
print(f"Shape of tensor: {rand_tensor.size()}")
print(f"Device tensor is on: {rand_tensor.device}")

tensor([[0.5956, 0.5017, 0.1806, 0.4144],
        [0.7325, 0.0361, 0.9959, 0.9043],
        [0.7127, 0.9013, 0.4089, 0.3233]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (Operations)

In [ ]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-build function
torch.mul(tensor, 10)   # Multiplication

tensor([10, 20, 30])

In [ ]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)    # Addition

tensor([11, 12, 13])

In [ ]:
torch.div(tensor, 10)    # Division

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.sub(tensor, 10)    # Subtraction

tensor([-9, -8, -7])

### Matrix multification

1. Element-wise Multification
2. Matrix multification (dot product)

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multification
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
tensor2 = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
tensor1.shape, tensor2.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
# Matrix Multification by hand
%%time
result = [[0 for _ in range(len(tensor2[0]))] for _ in range(len(tensor1))]

for i in range(len(tensor1)):
    for j in range(len(tensor2[0])):
        for k in range(len(tensor2)):
            result[i][j] += tensor1[i][k] * tensor2[k][j]

print(result)

[[tensor(50), tensor(68)], [tensor(122), tensor(167)]]
CPU times: user 2.31 ms, sys: 55 µs, total: 2.36 ms
Wall time: 5.63 ms


In [ ]:
%%time
torch.matmul(tensor1, tensor2)

CPU times: user 293 µs, sys: 1.04 ms, total: 1.34 ms
Wall time: 6.88 ms


tensor([[ 50,  68],
        [122, 167]])

In [ ]:
# Same as matmul
tensor1 @ tensor2

tensor([[ 50,  68],
        [122, 167]])

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor1, tensor2)

tensor([[ 50,  68],
        [122, 167]])

In [ ]:
# Transpose
tensor1.T, tensor2.T

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [ ]:
tensor1.T @ tensor2.T

tensor([[47, 52, 57],
        [64, 71, 78],
        [81, 90, 99]])

### Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [ ]:
# Find the mean
# Note : torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Positional min/max

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in that has the minimum value with argmin()
x.argmin()

tensor(0)

In [ ]:
# Find the position in that has the maximum value with argmax()
x.argmax()

tensor(9)

### Change tensor datatype

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype, tensor

(torch.float32, tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

#### Reshape

In [ ]:
x = torch.arange(1, 11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
# Add an extra dimention
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [ ]:
# Add an extra dimention
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

#### View

In [ ]:
# Change the view
y = x.view(1, 10)
y, y.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
# Changing y changes x (because a view of a tensor shares the same memory as the original input)
y[:, 0] = 5
y, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
z = x.view(5, 2)
z, z.shape

(tensor([[ 5,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [ ]:
z[:, 1] = 9
z, x

(tensor([[5, 9],
         [3, 9],
         [5, 9],
         [7, 9],
         [9, 9]]),
 tensor([5, 9, 3, 9, 5, 9, 7, 9, 9, 9]))

#### stack

In [ ]:
# Stacked tensors on top of each other
x = torch.arange(1, 11)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3],
         [ 4,  4,  4,  4],
         [ 5,  5,  5,  5],
         [ 6,  6,  6,  6],
         [ 7,  7,  7,  7],
         [ 8,  8,  8,  8],
         [ 9,  9,  9,  9],
         [10, 10, 10, 10]]),
 torch.Size([10, 4]))

In [ ]:
a = torch.rand(size=(2, 2))
a

tensor([[0.2122, 0.6183],
        [0.1838, 0.8702]])

In [ ]:
a_stacked_dim0 = torch.stack([a, a, a, a], dim=0)
a_stacked_dim1 = torch.stack([a, a, a, a], dim=1)
a_stacked_dim2 = torch.stack([a, a, a, a], dim=2)
a_stacked_dim0.shape, a_stacked_dim1.shape, a_stacked_dim2.shape

(torch.Size([4, 2, 2]), torch.Size([2, 4, 2]), torch.Size([2, 2, 4]))

In [ ]:
# Stack tensors in sequence vertically (row wise).
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack([a,b])   # No dim arguments

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
# Stack tensors in sequence horizontally (column wise)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.hstack([a,b])

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

#### Squeeze

In [ ]:
# Returns a tensor with all specified dimensions of input of size 1 removed.
x = torch.arange(1, 11)
x = x.reshape(10, 1)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
y = torch.squeeze(x)
y, y.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
y = torch.squeeze(x, 0)   # Here squeeze(vcariable, dim_index)
y.size()

torch.Size([10])

In [ ]:
z = torch.zeros(2, 1, 2, 1, 2)
y = torch.squeeze(z)
y_0 = torch.squeeze(z, 0)
y_1 = torch.squeeze(z, 1)
y_index = torch.squeeze(z, (1, 2, 3))
z.shape, y.shape, y_0.shape, y_1.shape, y_index.shape

(torch.Size([2, 1, 2, 1, 2]),
 torch.Size([2, 2, 2]),
 torch.Size([2, 1, 2, 1, 2]),
 torch.Size([2, 2, 1, 2]),
 torch.Size([2, 2, 2]))

In [ ]:
# Unsqueeze - Returns a new tensor with a dimension of size one inserted at the specified position.
x = torch.arange(1, 11)
y_0 = x.unsqueeze(dim=0)
y_1 = x.unsqueeze(dim=1)
x.shape, y_0.shape, y_1.shape

(torch.Size([10]), torch.Size([1, 10]), torch.Size([10, 1]))

#### Permute

In [ ]:
# Returns a view of the original tensor input with its dimensions permuted.
x = torch.randn(2, 3, 5)
x, x.size()

(tensor([[[-0.2483, -1.2082, -0.4777,  0.5201,  1.6423],
          [-0.1596, -0.4974,  0.4396,  2.0024,  0.4664],
          [ 1.5730, -0.9228,  1.2791,  1.2964,  1.5736]],
 
         [[-0.8455,  1.3123,  0.6872, -1.0892, -0.3553],
          [-0.9138, -0.6581,  0.0499,  2.2667,  1.1790],
          [-0.4345, -1.3864, -1.2862, -1.4032,  0.0360]]]),
 torch.Size([2, 3, 5]))

In [ ]:
torch.permute(x, (2, 0, 1)).size()   # 0, 1, 2 - index of the size

torch.Size([5, 2, 3])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))  # height, width, color
x_permuted = x_original.permute(2, 0, 1)   # color, height, width
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
# Share same memory
x_original[0, 0, 0] = 1234
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1234.), tensor(1234.))

### Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
x[0, 0, 1]

tensor(2)

In [ ]:
# Use ':' to select all of a target dimention
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

In [ ]:
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### PyTorch tensors & Numpy


    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [ ]:
# Numpy array to Tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float32)

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensorr to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

Trying to take the random out of random

To reduce the randomness in NN and PyTorch comes the concept of **random seed**.

In [ ]:
torch.rand(3, 3)

tensor([[0.0457, 0.5300, 0.5879],
        [0.9008, 0.5596, 0.6701],
        [0.3849, 0.0817, 0.9203]])

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.3325, 0.7083, 0.0874, 0.8898],
        [0.3710, 0.0355, 0.7920, 0.4443],
        [0.6232, 0.8682, 0.0390, 0.2127]])

Tensor B:
tensor([[0.4187, 0.6344, 0.5731, 0.6381],
        [0.8531, 0.1400, 0.6811, 0.8878],
        [0.2259, 0.9352, 0.9917, 0.6699]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Set the random seed
Random_seed = 42
torch.manual_seed(seed = Random_seed)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Set the random seed
Random_seed = 42
torch.manual_seed(seed = Random_seed)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed = Random_seed)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors on GPUs (and making faster computations)

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Sun Aug 25 07:50:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              11W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

For PyTorch since it's capble of running compute on the GPU & CPU. It's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
# Move tensor to GPU (if available)
tensor = torch.tensor([1, 2, 3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_cpu.numpy()

array([1, 2, 3])